import Head from 'next/head';

import { useForm, Controller } from 'react-hook-form';

import { Button } from '@/components/elements';
import {
  twitterIcon,
  linkedinIcon,
  githubIcon,
  messageIcon,
} from 'public/assets/icons';

const Contact = () => {
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm();

  return (
    <>
      <Head>
        <title>Chioma Otu - Frontend developer in Nigeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto px-4 py-10">
        <h1 className="uppercase text-darkRed text-2xl lg:text-[40px] font-bold">
          Contact me
        </h1>

        <div className="grid grid-cols-1 lg:grid-cols-9 gap-8 mt-8">
          <article className="col-span-4">
            <p className="text-base text-darkGray">
              Hey there! Have any question, want to collaborate with me, hire me
              for a project or just talk about tech stuff, send me a message and
              I’ll get back to you asap.
            </p>

            <div className="mt-10">
              <h2 className="font-semibold text-base">Connect with me</h2>

              <div className="flex items-center mt-3">
                <Button
                  styles="bg-transparent"
                  iconSrc={twitterIcon}
                  iconAlt="twitter icon"
                />

                <Button
                  styles="bg-transparent mx-5"
                  iconSrc={linkedinIcon}
                  iconAlt="linkedin icon"
                />

                <Button
                  styles="bg-transparent"
                  iconSrc={githubIcon}
                  iconAlt="github icon"
                />

                <Button
                  styles="bg-transparent ml-5"
                  iconSrc={messageIcon}
                  iconAlt="message icon"
                />
              </div>
            </div>
          </article>

          <article className="col-span-5">
            <form>
              <div className="lg:grid grid-cols-12 gap-4">
                <div className="col-span-6 mb-4 lg:mb-0">
                  <label className="block mb-3 text-lg text-dark-2 capitalize">
                    full name
                  </label>

                  <input
                    name="fullName"
                    className="w-full bg-white text-base py-4 px-2 border border-gray-300 rounded focus:outline-0 focus:border-darkRed"
                    type="text"
                    {...register('fullName', { required: true })}
                    placeholder="Full name"
                  />
                  {errors.fullName && (
                    <small className="text-red-400"> Name is required</small>
                  )}
                </div>

                <div className="col-span-6 mb-4 lg:mb-0">
                  <label className="block mb-3 text-lg text-darkGray capitalize">
                    email address
                  </label>
                  <input
                    name="email"
                    className="w-full bg-white text-base py-4 px-2 border border-gray-300 rounded focus:outline-0 focus:border-darkRed"
                    type="email"
                    placeholder="Email address"
                    {...register('email', {
                      required: true,
                      pattern: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
                    })}
                  />
                  {errors.email && (
                    <small className="text-red-400"> Email is required</small>
                  )}
                </div>

                <div className="col-span-12 ">
                  <label className="block mb-3 text-lg text-darkGray capitalize">
                    message
                  </label>
                  <textarea
                    name="message"
                    className=" rounded w-full h-40  px-2 py-3 bg-white border border-gray-300 focus:outline-0 focus:border-darkRed text-darkGray"
                    placeholder="Type in your message"
                    {...register('message', {
                      required: true,
                    })}
                  ></textarea>
                  {errors.message && (
                    <small className="text-red-400"> Message is required</small>
                  )}
                </div>
              </div>

              <div className="lg:w-fit mt-8">
                <Button text="send message" />
              </div>
            </form>
          </article>
        </div>
      </section>
    </>
  );
};

export default Contact;
