import Head from 'next/head';
import { TimeLineLarge, TimeLineMobile } from '@/components/sections';
import { Button } from '@/components/elements';

const Resume = () => {
  return (
    <>
      <Head>
        <title>Chioma Otu - Frontend developer in Nigeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container mx-auto px-4 py-10">
        <h1 className="uppercase text-darkRed text-2xl lg:text-[40px] font-bold">
          My Resume
        </h1>

        <div className="max-w-[960px] mx-auto">
          <TimeLineLarge />
          <TimeLineMobile />

          <div className="w-fit mx-auto">
            <Button text="download complete resume" />
          </div>
        </div>
      </section>
    </>
  );
};

export default Resume;
